name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: clean
        run: ./gradlew clean
        
  build:
    runs-on: ubuntu-latest        
    
    steps:
      - name: build
        run: ./gradlew build
        
  checkstyle:
    runs-on: ubuntu-latest        
    
    steps:      
      - name: checkstyle
        run: ./gradlew checkstyleMain checkstyleTest -i
        
  test:
    runs-on: ubuntu-latest        
    
    steps:       
      - name: test
        run: ./gradlew test

